# Generated by Django 4.0.2 on 2022-03-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Базовая цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('components', models.CharField(max_length=255, verbose_name='Состав')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza.category')),
            ],
        ),
    ]
